#!/bin/sh
#
# /usr/sbin/nhs
#
# Nethome Server instance control script
# Calls all present /etc/init.d/nhs-daemon service start script.
# Hence, it handles all installed service components with a single
# command.

# read central configuration (not yet created!)
# . /etc/opt/nhs.properties || exit 1
NHS_DAEMON_NAME=_NHS_DAEMON_

usage()
{
    if [ ! -z "$1" ]; then 
        echo "$0: $1" >&2
    fi
    echo "Usage: $0 {start|stop|status|restart|force-reload}" >&2
}

# no argument - show help
if [ $# -eq 0 ]; then
    usage
    exit 0
fi


# read arguments
cmd=""

while [ $# -gt 0 ]; do
    case "$1" in
        'start'|'stop'|'status'|'restart'|'force-reload')
            cmd=$1
            ;;
        *)
            usage "unknown argument: $1"
            exit 1
            ;;
    esac
    shift
done    

# default to return success; set to error if
# at least one service call fails
r=0

# now pass the command to init script
case $cmd in

    'start'|'stop'|'status')
		script="/etc/init.d/$NHS_DAEMON_NAME"
		if [ -x $script ]; then
			$script $cmd
			if [ $? != "0" ]; then r=1; fi
		fi
        ;;

    'restart'|'force-reload')
		script="/etc/init.d/$NHS_DAEMON_NAME"
		if [ -x $script ]; then
			$script stop
			if [ $? != "0" ]; then r=1; fi
		fi
        sleep 1
		script="/etc/init.d/$NHS_DAEMON_NAME"
		if [ -x $script ]; then
			$script start
			if [ $? != "0" ]; then r=1; fi
		fi
        ;;

    *)
        usage "command argument missed"
        exit 1
        ;;
esac

exit $r
